# Generated by Django 5.1.1 on 2024-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('depatment', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=30)),
                ('rollnumber', models.IntegerField()),
            ],
        ),
    ]
